openapi: 3.0.3
info:
  title: MedAssist Auth Service API
  description: |
    Authentication and authorization service for MedAssist platform.
    
    ## ⚠️ Medical Disclaimer
    MedAssist is a platform for purchasing OTC and prescription medicines. 
    Always consult with a qualified healthcare professional before taking any medication.
  version: 1.0.0
  contact:
    name: MedAssist Team
    email: support@medassist.com

servers:
  - url: http://localhost:3001
    description: Development server

tags:
  - name: Authentication
    description: User authentication endpoints
  - name: Admin
    description: Admin-only endpoints
  - name: Monitoring
    description: Health and metrics

paths:
  /api/v1/auth/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      description: Creates a new user account and sends OTP to phone for verification
      operationId: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - phone
                - password
              properties:
                name:
                  type: string
                  example: John Doe
                email:
                  type: string
                  format: email
                  example: john@example.com
                phone:
                  type: string
                  pattern: '^\+?[1-9]\d{9,14}$'
                  example: "+919876543210"
                password:
                  type: string
                  minLength: 8
                  example: secureP@ss123
      responses:
        '201':
          description: Registration successful, OTP sent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Email or phone already exists
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/auth/verify-otp:
    post:
      tags:
        - Authentication
      summary: Verify phone OTP
      description: Verifies the OTP sent to user's phone and activates the account
      operationId: verifyOtp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - phone
                - otp
              properties:
                phone:
                  type: string
                  example: "+919876543210"
                otp:
                  type: string
                  pattern: '^\d{6}$'
                  example: "123456"
      responses:
        '200':
          description: OTP verified, tokens issued
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '400':
          description: Invalid or expired OTP
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/auth/login:
    post:
      tags:
        - Authentication
      summary: Login
      description: Authenticates user with email/phone and password
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email_or_phone
                - password
              properties:
                email_or_phone:
                  type: string
                  example: john@example.com
                password:
                  type: string
                  example: secureP@ss123
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '401':
          description: Invalid credentials
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too many attempts
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/auth/refresh:
    post:
      tags:
        - Authentication
      summary: Refresh access token
      description: Uses refresh token to obtain a new access token
      operationId: refresh
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - refresh_token
              properties:
                refresh_token:
                  type: string
      responses:
        '200':
          description: New tokens issued
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthTokenResponse'
        '401':
          description: Invalid or expired refresh token
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/auth/logout:
    post:
      tags:
        - Authentication
      summary: Logout
      description: Revokes the refresh token
      operationId: logout
      security:
        - bearerAuth: []
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
      responses:
        '200':
          description: Logout successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /api/v1/auth/admin/create-pharmacist:
    post:
      tags:
        - Admin
      summary: Create pharmacist account
      description: Admin creates a new pharmacist account
      operationId: createPharmacist
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - email
                - phone
                - password
                - pharmacy_name
                - pharmacy_address
              properties:
                name:
                  type: string
                email:
                  type: string
                  format: email
                phone:
                  type: string
                password:
                  type: string
                pharmacy_name:
                  type: string
                pharmacy_address:
                  type: string
                pharmacy_lat:
                  type: number
                pharmacy_lon:
                  type: number
      responses:
        '201':
          description: Pharmacist created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '403':
          description: Forbidden - admin only
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/auth/admin/create-driver:
    post:
      tags:
        - Admin
      summary: Create driver account
      description: Admin creates a new driver account with username driver_<id>
      operationId: createDriver
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - phone
                - password
              properties:
                name:
                  type: string
                phone:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Driver created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '403':
          description: Forbidden - admin only
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /health:
    get:
      tags:
        - Monitoring
      summary: Health check
      operationId: healthCheck
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
                  service:
                    type: string
                    example: auth-service
                  timestamp:
                    type: string
                    format: date-time

  /metrics:
    get:
      tags:
        - Monitoring
      summary: Prometheus metrics
      operationId: getMetrics
      responses:
        '200':
          description: Prometheus metrics
          content:
            text/plain:
              schema:
                type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object

    AuthTokenResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true
        data:
          type: object
          properties:
            access_token:
              type: string
            refresh_token:
              type: string
            expires_in:
              type: integer
              example: 900
            roles:
              type: array
              items:
                type: string
              example: ["user"]

    ErrorResponse:
      type: object
      properties:
        error_code:
          type: string
          example: VALIDATION_ERROR
        message:
          type: string
          example: Invalid input data
        details:
          type: object
