openapi: 3.0.3
info:
  title: MedAssist Driver Service API
  description: |
    Driver delivery management service.
    
    ## ⚠️ Medical Disclaimer
    MedAssist is a platform for purchasing OTC and prescription medicines.
    Always consult with a qualified healthcare professional before taking any medication.
  version: 1.0.0
  contact:
    name: MedAssist Team
    email: support@medassist.com

servers:
  - url: http://localhost:8002
    description: Development server

tags:
  - name: Deliveries
    description: Delivery management endpoints
  - name: Profile
    description: Driver profile endpoints

paths:
  /api/v1/driver/deliveries:
    get:
      tags:
        - Deliveries
      summary: Get deliveries
      description: Get all deliveries assigned to or available for the driver
      operationId: listDeliveries
      security:
        - bearerAuth: []
      parameters:
        - name: status
          in: query
          schema:
            type: string
            enum: [pending, assigned, picked_up, in_transit, delivered, failed]
        - name: available
          in: query
          description: Show available deliveries to accept
          schema:
            type: boolean
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: size
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Delivery list
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryListResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/driver/deliveries/{id}:
    get:
      tags:
        - Deliveries
      summary: Get delivery details
      description: Get details of a specific delivery
      operationId: getDelivery
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Delivery details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryResponse'
        '404':
          description: Delivery not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/driver/deliveries/{id}/accept:
    post:
      tags:
        - Deliveries
      summary: Accept delivery
      description: Accept a pending delivery
      operationId: acceptDelivery
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Delivery accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryResponse'
        '400':
          description: Cannot accept - already assigned or invalid status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '409':
          description: Conflict - delivery already assigned to another driver
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/driver/deliveries/{id}/status:
    post:
      tags:
        - Deliveries
      summary: Update delivery status
      description: Update delivery status and optionally location
      operationId: updateDeliveryStatus
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateStatusRequest'
      responses:
        '200':
          description: Status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryResponse'
        '400':
          description: Invalid status transition
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/driver/deliveries/{id}/confirm-delivery:
    post:
      tags:
        - Deliveries
      summary: Confirm delivery with OTP
      description: Complete delivery by verifying customer OTP
      operationId: confirmDelivery
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - otp
              properties:
                otp:
                  type: string
                  pattern: '^\d{4,6}$'
                  example: "1234"
                notes:
                  type: string
                  description: Delivery notes
      responses:
        '200':
          description: Delivery confirmed
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DeliveryResponse'
        '400':
          description: Invalid OTP or wrong status
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/v1/driver/profile:
    get:
      tags:
        - Profile
      summary: Get driver profile
      description: Get the driver's profile and stats
      operationId: getProfile
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Profile details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProfileResponse'

  /api/v1/driver/location:
    put:
      tags:
        - Profile
      summary: Update driver location
      description: Update the driver's current location
      operationId: updateLocation
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - lat
                - lon
              properties:
                lat:
                  type: number
                  minimum: -90
                  maximum: 90
                lon:
                  type: number
                  minimum: -180
                  maximum: 180
      responses:
        '200':
          description: Location updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'

  /health:
    get:
      summary: Health check
      responses:
        '200':
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  service:
                    type: string

  /metrics:
    get:
      summary: Prometheus metrics
      responses:
        '200':
          description: Metrics in Prometheus format
          content:
            text/plain:
              schema:
                type: string

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    DeliveryListResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            deliveries:
              type: array
              items:
                $ref: '#/components/schemas/Delivery'
            total:
              type: integer
            page:
              type: integer

    DeliveryResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            delivery:
              $ref: '#/components/schemas/Delivery'

    Delivery:
      type: object
      properties:
        _id:
          type: string
        order_id:
          type: string
        driver_id:
          type: string
        status:
          type: string
          enum: [pending, assigned, picked_up, in_transit, delivered, failed]
        assigned_at:
          type: string
          format: date-time
        pickup_at:
          type: string
          format: date-time
        delivered_at:
          type: string
          format: date-time
        current_location:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
        pickup_address:
          type: object
          properties:
            pharmacy_name:
              type: string
            address:
              type: string
            phone:
              type: string
            lat:
              type: number
            lon:
              type: number
        delivery_address:
          type: object
          properties:
            customer_name:
              type: string
            address_line:
              type: string
            city:
              type: string
            pincode:
              type: string
            phone:
              type: string
            lat:
              type: number
            lon:
              type: number
        order_details:
          type: object
          properties:
            items_count:
              type: integer
            total_amount:
              type: number

    UpdateStatusRequest:
      type: object
      required:
        - status
      properties:
        status:
          type: string
          enum: [picked_up, in_transit, failed]
        lat:
          type: number
        lon:
          type: number
        notes:
          type: string

    ProfileResponse:
      type: object
      properties:
        success:
          type: boolean
        data:
          type: object
          properties:
            driver:
              type: object
              properties:
                _id:
                  type: string
                name:
                  type: string
                phone:
                  type: string
                email:
                  type: string
                current_location:
                  type: object
                  properties:
                    lat:
                      type: number
                    lon:
                      type: number
            stats:
              type: object
              properties:
                total_deliveries:
                  type: integer
                completed_today:
                  type: integer
                pending:
                  type: integer
                rating:
                  type: number

    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string

    ErrorResponse:
      type: object
      properties:
        error_code:
          type: string
        message:
          type: string
        details:
          type: object
